research_areas_c = {
    'Communication': '708',
    'Public, Environmental & Occupational Health': '416',
    'Multidisciplinary Sciences': '264',
    'Psychology, Experimental': '217',
    'Medicine, General & Internal': '206',
    'Information Science & Library Science': '179',
    'Political Science': '153',
    'Psychology, Multidisciplinary': '152',
    'Health Care Sciences & Services; Medical Informatics': '108',
    'Education & Educational Research': '105',
    'Environmental Sciences; Public, Environmental & Occupational Health': '102',
    'Social Sciences, Interdisciplinary': '93',
    'Immunology; Medicine, Research & Experimental': '85',
    'Computer Science, Information Systems; Information Science & Library Science': '74',
    'Computer Science, Information Systems': '73',
    'Communication; Information Science & Library Science': '68',
    'Law': '65',
    'Nursing': '62',
    'International Relations': '58',
    'Communication; Political Science': '57',
    'Obstetrics & Gynecology': '56',
    'Psychology, Social': '53',
    'Pediatrics': '46',
    'Psychiatry': '44',
    'Humanities, Multidisciplinary': '42',
    'Pharmacology & Pharmacy': '41',
    'History': '40',
    'Urology & Nephrology': '40',
    'Communication; Health Policy & Services': '38',
    'Computer Science, Information Systems; Engineering, Electrical & Electronic; Telecommunications': '38',
    'Computer Science, Artificial Intelligence': '37',
    'Dermatology': '37',
    'Oncology': '37',
    'Communication; Sociology': '36',
    'Biotechnology & Applied Microbiology; Immunology': '34',
    'Psychology, Clinical; Social Sciences, Interdisciplinary': '34',
    'Health Care Sciences & Services': '32',
    'Sociology': '32',
    'Health Care Sciences & Services; Health Policy & Services': '31',
    'Economics': '30',
}
