# Generated by Django 4.1.2 on 2022-12-07 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('corpusid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('abstract', models.CharField(max_length=500)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'public.abstract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('corpus_paper_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('year', models.FloatField()),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('corpusid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('referencecount', models.PositiveIntegerField()),
                ('citationcount', models.PositiveIntegerField()),
                ('influentialcitationcount', models.PositiveIntegerField()),
                ('isopenaccess', models.BooleanField()),
                ('venue', models.CharField(max_length=500)),
                ('s2fieldsofstudy', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('publicationtypes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('publicationdate', models.DateField()),
                ('paperyear', models.PositiveIntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'public.papers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paper_SeSc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpusid', models.PositiveIntegerField()),
                ('in_scope', models.BooleanField()),
                ('comment', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
