# Generated by Django 4.1.2 on 2022-12-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misinfo_main', '0002_alter_paper_sesc_comment_alter_paper_sesc_in_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PaperClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper_sesc',
            name='in_scope',
        ),
        migrations.AddField(
            model_name='paper_sesc',
            name='dbquery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misinfo_main.dbquery'),
        ),
        migrations.AddField(
            model_name='paper_sesc',
            name='paperclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='query_paper_sesc', to='misinfo_main.dbquery'),
            preserve_default=False,
        ),
    ]
