# Generated by Django 4.1.2 on 2022-12-15 17:39

from django.db import migrations

def create_paperclass(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    paperclass_model = apps.get_model('misinfo_main', 'PaperClassification')
    paperclass_model.objects.get_or_create(name='In Scope', )
    paperclass_model.objects.get_or_create(name='Out of Scope', )
    #paperclass_model.objects.get_or_create(name='To Analyze', )


class Migration(migrations.Migration):

    dependencies = [
        ('misinfo_main', '0003_dbquery_paperclassification_and_more'),
    ]

    operations = [
        migrations.RunPython(create_paperclass)
    ]
