# Generated by Django 4.1.2 on 2022-12-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misinfo_main', '0004_auto_20221215_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_sesc',
            name='paperclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_paper_sesc', to='misinfo_main.paperclassification'),
        ),
    ]
