# Generated by Django 4.1.2 on 2022-12-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misinfo_main', '0006_paper_sesc_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_sesc',
            name='abstract',
            field=models.TextField(default='abstract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper_sesc',
            name='url_sesc',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_sesc',
            name='paperclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_paper_sesc', to='misinfo_main.paperclassification'),
        ),
    ]
