# Generated by Django 4.1.2 on 2022-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misinfo_main', '0007_paper_sesc_abstract_paper_sesc_url_sesc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper_sesc',
            options={'verbose_name': 'Paper', 'verbose_name_plural': 'Papers'},
        ),
        migrations.AddField(
            model_name='dbquery',
            name='is_fetching',
            field=models.BooleanField(default=False),
        ),
    ]
